replicaCount: 3

image:
  repository: ghcr.io/dhaluwinrune/hello-world-nginx
  tag: latest
  pullPolicy: Always

namespace: rune

service:
  type: NodePort
  port: 80
  nodePort: 30080

deployment:
  name: hello-world-deployment

labels:
  app: hello-world
