name: Azure Test Pipeline

on:
  workflow_dispatch:

jobs:
  azure-cli-demo:
    runs-on: ubuntu-latest  # ook op Windows mogelijk, maar Linux is standaard sneller
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure test - Get Compute
        uses: Azure/CLI@v2.1.0
        with:
          azcliversion: 2.64.0
          inlineScript: |
            az extension add --name ml
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml compute list
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS }} # Je kan eventueel hieruit dynamisch info halen (optioneel)
